# Generated by Django 3.1.3 on 2020-11-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='vin',
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=64, verbose_name='name'),
            preserve_default=False,
        ),
    ]
